/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: rahumbarger27 (https://sketchfab.com/rahumbarger27)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blocks-e3455b13c1a14ca69962d5f5fa2f3efa
Title: Blocks
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Blocks() {
  const { nodes, materials } = useGLTF(
    "/demo-2025-interactive-rug/blocks.glb"
  ) as any;
  return (
    <>
      <group dispose={null} scale={0.2}>
        <group position={[0, 0, 3.709]}>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Block2_pasted__blinn20_0.geometry}
              material={materials.pasted__blinn20}
              position={[-0.895, -0.002, -2]}
            />
          </RigidBody>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.bevel_block2_pasted__blinn21_0.geometry}
              material={materials.pasted__blinn21}
              position={[-2.379, 0, -2.005]}
            />
          </RigidBody>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cylinder_block1_pasted__blinn18_0.geometry}
              material={materials.pasted__blinn18}
              position={[-13.63, 0, -2.003]}
            />
          </RigidBody>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wedge_block3_pasted__blinn19_0.geometry}
              material={materials.pasted__blinn19}
              position={[11.672, 7, -2]}
            />
          </RigidBody>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wedge_block4_pasted__blinn19_0.geometry}
              material={materials.pasted__blinn19}
              position={[-11.672, 7, 1.5]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
          </RigidBody>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.bevel_block1_pasted__blinn21_0.geometry}
              material={materials.pasted__blinn21}
              position={[2.457, 0, 1.505]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
          </RigidBody>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Block1_pasted__blinn20_0.geometry}
              material={materials.pasted__blinn20}
              position={[5.888, -0.002, -2]}
            />
          </RigidBody>
          <RigidBody type="dynamic" colliders="hull">
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cylinder_block4_pasted__blinn18_0.geometry}
              material={materials.pasted__blinn18}
              position={[7.2, 0, -2.003]}
            />
          </RigidBody>
        </group>
      </group>

      {/* Death plane */}
      <RigidBody
        type="fixed"
        colliders="cuboid"
        position={[0, -10, 0]}
        onCollisionEnter={(e) => {
          e.rigidBody?.setLinvel({ x: 0, y: 0, z: 0 }, true);
          e.rigidBody?.setAngvel({ x: 0, y: 0, z: 0 }, true);
          e.rigidBody?.setTranslation({ x: 0, y: 5, z: 0 }, true);
        }}
      >
        <mesh rotation-x={-Math.PI / 2} position={[0, -0.001, 0]}>
          <planeGeometry args={[500, 500]} />
          <meshBasicMaterial color="#4E6688" toneMapped={false} />
        </mesh>
      </RigidBody>
    </>
  );
}
